### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by mhvezina**
small fixes. A last verification in context might be necessary.

### CODE REVIEW

**Comment by kaitlinnewson** [comment]
@mhvezina within Dataverse, RData is the same in both English and French - shouldn't this stay the same since it's the formal name of the file format?

**Comment by mhvezina** [comment]
@kaitlinnewson I changed "rdata_format":"Fichier au format RData" to "rdata_format":"Fichier au format RDA" just to match the English version: https://github.com/scholarsportal/Dataverse-Data-Explorer/blob/master/assets/js/english.json#L34

**Comment by kaitlinnewson** [comment]
@mhvezina Ah, I see! That's incorrect as well, so I'm going to adjust that.

**Comment by mhvezina** [comment]
@kaitlinnewson Ok. thanks. So you can also bring back the former French version "Fichier au format RData".

**Pull request merged**
